baseURL = "https://iamtu.dev"
languageCode = "en-us"
title = "iamtu.dev"
theme="archie"
copyright = "© iamtu_ricatto"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "iamtu-dev"

paginate=5 # articles per page



[params]
	mode="toggle" 	# color-mode → light,dark,toggle or auto
	useCDN=false 	# don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "I am 29 (as of 2022). My undergrad was Economics at a local university, and I am going back to school so I can pursue higher education in the field of Machine Learning & Artificial Intelligence." 
	mathjax = true 	# enable MathJax support
	katex = true 	# enable KaTeX support

# Social Tags

[[params.social]]
name = "young1906"
icon = "github"
url = "https://github.com/young1906"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publication"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
