baseURL = "https://iamtu.dev"
languageCode = "en-us"
title = "iamtu.dev"
theme = "paper"
disqusShortname = "iamtu-dev"
copyright = "© iamtu_ricatto"

[params]
  # color style
  color = 'toggle'                           # linen, wheat, gray, light

  # header social icons
  github = 'young1906'
  instagram = 'tutdo93'
  linkedin = 'tu.dothanh'

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Tu T. Do'
  bio = ""
  math = true
  mathjax = true
  katex = true


[[menu.main]]
name = "Home"
url = "/"
weight = 1

# [[menu.main]]
# name = "Publications"
# url = "/publication"
# weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
