baseURL = "https://iamtu.dev"
languageCode = "en-us"
title = "iamtu.dev"
theme="archie"
copyright = "© iamtu_ricatto"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"

paginate=5 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=true# don't use CDNs for fonts and icons, instead serve them locally.
	# subtitle = "I'm into drawing chart and browsing meme."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "young1906"
icon = "github"
url = "https://github.com/young1906"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
